version: '3'
services:
  news_service_db:
    image: postgres:14
    container_name: news_service_db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - PGPORT=${PG_PORT}
    expose:
      - 5434
    ports:
      - 5434:5432
    command: -p 5434
    networks:
      - djangonetwork
  
  web:
    build: .
    container_name: news_service
    command: python ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    depends_on:
      - news_service_db
    links:
      - news_service_db:news_service_db
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge

volumes:
  pgdata: