# Generated by Django 5.0.1 on 2024-01-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsserviceapp', '0004_comment_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='isLiked',
        ),
    ]
